# Generated by Django 3.2.23 on 2024-06-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_comment_post_role_topic_user_accaunt_delete_posts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False, 'ordering': ('publish_datetime',)},
        ),
    ]
